
package edu.z1.euler

import scala.annotation.tailrec
import scala.util.control.Breaks.{break, breakable}

/**
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose
 * values do not exceed four million, find the sum of
 * the even-valued terms.
 */

object Problem2 {

  import scala.annotation.tailrec

  private def fibonacciTailRec(n: Int): BigInt = {
    @tailrec
    def fibHelper(i: Int, current: BigInt, next: BigInt): BigInt = {
      if (i == 0) {
        current
      }
      else {
        fibHelper(i - 1, next, current + next)
      }
    }

    fibHelper(n, 0, 1)
  }

  def evenFibonacciNums(below: Int): BigInt = {
    var evenFibNumsSum: BigInt = 0
    breakable {
      for (i <- 0 to 100) {
        val fibValue = fibonacciTailRec(i)
        if (fibValue <= below) {
          if (fibValue % 2 == 0) {
            evenFibNumsSum += fibValue
          }
        }
        else {
          break
        }
      }
    }
    evenFibNumsSum
  }

}
