
package edu.z1.euler

import org.scalatest._

/**
  * Each new term in the Fibonacci sequence is generated by
  * adding the previous two terms. By starting with 1 and 2,
  * the first 10 terms will be:
  * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  *
  * By considering the terms in the Fibonacci sequence whose
  * values do not exceed four million, find the sum of the even-valued terms.
  */
class Problem2Spec() extends FlatSpec {

  "P2: sum of even fibbonacci numbers below 10 " should " be equal 10" in {
    assert(Problem2.evenFibonacciNums(10) == 10)
  }

  "P2: sum of even fibonacci numbers below 4m " should " be equal 4613732" in {
    assert(Problem2.evenFibonacciNums(4000000) == 4613732)
  }

}
